CUDA_VISIBLE_DEVICES=4,5,6,7 python run_true_removal.py \
	--train_file /home/v-lizimeng/data/WebSRC/websrc1.0_train_.json \
	--root_dir /home/v-lizimeng/data/WebSRC \
	--model_name_or_path microsoft/markuplm-large \
	--output_dir /home/v-lizimeng/unilm/markuplm/examples/fine_tuning/run_websrc/results_true_removal_25_L \
	--do_train \
	--save_steps 2000 \
	--max_query_length 42 \
	--max_seq_length 512 \
	--learning_rate 1e-5 \
	--per_gpu_train_batch_size 4 \
	--warmup_ratio 0.1 \
	--num_train_epochs 5 \
	--max_num_nodes 92 \
	--num_removed_nodes 25
