CUDA_VISIBLE_DEVICES=6,7 python run_node_removal.py \
	--train_file /home/v-lizimeng/data/WebSRC/websrc1.0_train_.json \
	--root_dir /home/v-lizimeng/data/WebSRC \
	--model_name_or_path microsoft/markuplm-base \
	--output_dir /home/v-lizimeng/unilm/markuplm/examples/fine_tuning/run_websrc/results_node_removal \
	--do_train \
	--save_steps 1000 \
	--max_query_length 42 \
	--max_seq_length 512 \
	--learning_rate 1e-5 \
	--per_gpu_train_batch_size 8 \
	--warmup_ratio 0.1 \
	--num_train_epochs 5 \
	--max_num_nodes 96
